environments:
  test:

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami/

releases:
  - name: metrics-server
    namespace: kube-system
    chart: bitnami/metrics-server
    version: 5.8.11
